from graphics import circle,rectangle,cubiod,sphere
r=int(input("enter the radius of circle"))
circle.areac(r)
circle.peric(r)
l=int(input("enter the length of rectangle"))
b=int(input("enter the breadth of rectangle"))
rectangle.arear(l,b)
rectangle.perir(l,b)
l1=int(input("enter the length of cuboid"))
b1=int(input("enter the breadth of cuboid"))
h1=int(input("enter the height of cuboid"))
cubiod.areacub(l1,b1,h1)
cubiod.pericub(l1,b1,h1)
r1=int(input("enter the radius of sphere"))
sphere.areas(r1)
sphere.peris(r1)